name: Continuous Delivery
on:
  push:
    branches:
    - main


jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.0.0
        with: 
         dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Publish Package
        run: dotnet publish ./RestaurantApi3/RestaurantApi3.csproj -c Release -o ${{env.DOTNET_ROOT}}/api
      - name: Upload a Build Artifact restaurantapi-artifact
        uses: actions/upload-artifact@v4.3.0
        with:
          name: restaurantapi-artifact
          path: ${{env.DOTNET_ROOT}}/api


  deploy-dev:
    name: Deploy to dev
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'development'
      url: ${{steps.deploy-to-azure.outputs.webapp-url}}
    steps:
      - name: Download a Build Artifact restaurantapi-artifact
        uses: actions/download-artifact@v4.1.1
        with:
          name: restaurantapi-artifact
      - name: Deploy to Azure WebApp
        id: deploy-to-azure
        uses: Azure/webapps-deploy@v3.0.0
        with:
          app-name: restaurantapi-devv
          publish-profile: ${{secrets.PUBLISH_PROFILE_DEV}}

  deploy-stage:
    name: Deploy to stage
    runs-on: ubuntu-latest
    needs: deploy-dev
    environment:
      name: 'stage'
      url: ${{steps.deploy-to-azure.outputs.webapp-url}}
    steps:
      - name: Download a Build Artifact restaurantapi-artifact
        uses: actions/download-artifact@v4.1.1
        with:
          name: restaurantapi-artifact
      - name: Deploy to Azure WebApp
        id: deploy-to-azure
        uses: Azure/webapps-deploy@v3.0.0
        with:
          app-name: restaurantapi-stage
          publish-profile: ${{secrets.PUBLISH_PROFILE_STAGE}}


      
